### ISSUE TITLE
I've gotten an error that says "OpenAssets::Provider::ApiError: Unauthorized"

### ISSUE THREAD

**Issue by NishidaRyu416** [haw-itn/openassets-ruby#16]
code below
```
api = OpenAssets::Api.new({:network => 'testnet',
                           :provider => 'bitcoind', :cache => 'testnet.db',
                           :dust_limit => 600, :default_fees => 10000,
                           :min_confirmation => 1, :max_confirmation => 9999999,
                           :rpc => {:user => 'ryu.nishida', :password => 'pass',
                                    :schema => 'http', :port => 18332,
                                    :host => 'localhost'}})

```
then i got 

```
#<OpenAssets::Api:0x007fc4e0135a68 @config={:network=>"testnet", :provider=>"bitcoind", :cache=>"testnet.db", :dust_limit=>600, :default_fees=>10000, :min_confirmation=>1, :max_confirmation=>9999999, :rpc=>{:user=>"ryu.nishida", :password=>"pass", :schema=>"http", :port=>18332, :host=>"localhost"}}, @provider=#<OpenAssets::Provider::BitcoinCoreProvider:0x007fc4e124dc88 @config={:user=>"ryu.nishida", :password=>"416Nishida", :schema=>"http", :port=>18332, :host=>"localhost"}>, @tx_cache=#<OpenAssets::Cache::TransactionCache:0x007fc4e1c2ab20 @db=#<SQLite3::Database:0x007fc4e1c2aaf8 @tracefunc=nil, @authorizer=nil, @encoding=#<Encoding:UTF-8>, @busy_handler=nil, @collations={}, @functions={}, @results_as_hash=nil, @type_translation=nil, @readonly=false>>, @output_cache=#<OpenAssets::Cache::OutputCache:0x007fc4e0557d30 @db=#<SQLite3::Database:0x007fc4e0557d08 @tracefunc=nil, @authorizer=nil, @encoding=#<Encoding:UTF-8>, @busy_handler=nil, @collations={}, @functions={}, @results_as_hash=nil, @type_translation=nil, @readonly=false>>>

```
maybe i could succeed to get.

but and then i've gotten the error after i've enter the code below

```
api.getbalance

=>OpenAssets::Provider::ApiError: Unauthorized

```
How can i fix the error?

**Comment by azuchi** [comment]
When sending an RPC request to bitcoind, authentication seems to have failed.

maybe, the `user` or `password`  is wrong or access from the target IP is not permitted.

**Comment by NishidaRyu416** [comment]
How can I know the password or user whether wrong or right?
 In all likelihood, the IP is permitted but I want to check how can i do?

**Comment by azuchi** [comment]
you can check rpc connection using curl.

```
$ curl --user <user>:<password> --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:18332/ -w '%{http_code}\n'
```

**Comment by NishidaRyu416** [comment]
Is user and password my pc's? or bitcoin.conf's?

**Comment by azuchi** [comment]
bitcoin.conf

**Comment by NishidaRyu416** [comment]
I got 401,so it was not permitted.
my bitcoin.conf below
```
rpcuser=ryunishida
rpcpassword=416Nishida

HOST=localhost

server=1
txindex=1

rpcport=18332
testnet=3

```

**Comment by azuchi** [comment]
What is the environment (OS) , and in which directory is bitcoin.conf located?

**Comment by NishidaRyu416** [comment]
MacOSX10.12.6 and Macintosh 
```
HD/Users/nishidaryu/RubymineProjects/transgift/bitcoin/bitcoin.conf
```
Looking forward to your reply.

**Comment by azuchi** [comment]
path is incorrect.

see https://en.bitcoin.it/wiki/Running_Bitcoin#Bitcoin.conf_Configuration_File

**Comment by NishidaRyu416** [comment]
I need to follow typical path or default ?

**Comment by NishidaRyu416** [comment]
I enter the code below

```
curl --user ryunishida:password --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:18332/ -w '%{http_code}\n'

```

Then I got 

```
000
curl: (7) Failed to connect to 127.0.0.1 port 18332: Connection refused

```

**Comment by azuchi** [comment]
Maybe caused by your environment or configuration file. 
It is not a problem of openassets-ruby.

**Comment by NishidaRyu416** [comment]
Yes,I think so.
Thank you for answering.

**Comment by NishidaRyu416** [comment]
I repaired the error however i got same error

**Comment by NishidaRyu416** [comment]
```
OpenAssets::Provider::ApiError: Unauthorized
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openassets-ruby-0.6.5/lib/openassets/provider/bitcoin_core_provider.rb:117:in `block in request'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `process_result'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openassets-ruby-0.6.5/lib/openassets/provider/bitcoin_core_provider.rb:125:in `post'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openassets-ruby-0.6.5/lib/openassets/provider/bitcoin_core_provider.rb:116:in `request'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openassets-ruby-0.6.5/lib/openassets/provider/bitcoin_core_provider.rb:38:in `list_unspent'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openassets-ruby-0.6.5/lib/openassets/api.rb:202:in `get_unspent_outputs'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openassets-ruby-0.6.5/lib/openassets/medhod_filter.rb:41:in `call'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openassets-ruby-0.6.5/lib/openassets/medhod_filter.rb:41:in `block in method_added'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openassets-ruby-0.6.5/lib/openassets/api.rb:57:in `get_balance'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openassets-ruby-0.6.5/lib/openassets/medhod_filter.rb:41:in `call'
	from /Users/nishidaryu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/openassets-ruby-0.6.5/lib/openassets/medhod_filter.rb:41:in `block in method_added'
	from (irb):9
	from /Users/nishidaryu/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'

```

**Comment by NishidaRyu416** [comment]
'cause i gould get 200 after as i was told, I entered the curl.

```
 *   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 18332 (#0)
* Server auth using Basic with user 'ryunishida'
> POST / HTTP/1.1
> Host: 127.0.0.1:18332
> Authorization: Basic cnl1bmlzaGlkYTo0MTZOaXNoaWRh
> User-Agent: curl/7.54.0
> Accept: */*
> content-type: text/plain;
> Content-Length: 71
> 
* upload completely sent off: 71 out of 71 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 22 Aug 2017 09:45:28 GMT
< Content-Length: 626
< 
{"result":{"deprecation-warning":"WARNING: getinfo is deprecated and will be fully removed in 0.16. Projects should transition to using getblockchaininfo, getnetworkinfo, and getwalletinfo before upgrading to 0.16","version":159900,"protocolversion":70015,"walletversion":139900,"balance":0.00000000,"blocks":308062,"timeoffset":-2,"connections":4,"proxy":"","difficulty":1,"testnet":true,"keypoololdest":1503393418,"keypoolsize":2000,"paytxfee":0.00000000,"relayfee":0.00001000,"errors":"This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"},"error":null,"id":"curltest"}
* Connection #0 to host 127.0.0.1 left intact
200


```
